version: '3'
services:
  db:
    container_name: mysql-db
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: your_root_password
      MYSQL_DATABASE: your_database_name
    ports:
     - '3306:3306'

    volumes:

    - ./mysql-data:/var/lib/mysql
